config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'spots#index'
  
  resources :spots do               #こちらの２行を追加
    resource :likes, only: [:create, :destroy] 
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, {presence: true}
  validates :spot_id, {presence: true}

  belongs_to :user
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :likes, dependent: :destroy

  def liked?(spot)
    self.likes.exists?(spot_id: spot.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(spot_id: params[:spot_id])
    redirect_back(fallback_location: root_path )
  end

  def destroy
    @like = current_user.likes.find_by(spot_id: params[:spot_id])
    @like.destroy
    redirect_back(fallback_location: root_path )
  end
  
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  def index
    @spots = Spot.all
    @spot = Spot.find_by(id: params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavoriteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <header>
      <div class='header-logo'>
        <%= link_to('トップページ', '/') %>
      </div>
      <div class='header-menu'>
        <%- if current_user %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %><br />

        <%- else %>
          <%- if controller_name != 'sessions' %>
              <%= link_to "ログイン", new_session_path(resource_name) %><br />
          <% end %>

          <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
              <%= link_to "アカウント作成", new_registration_path(resource_name) %><br />
          <% end %>

        <%- end %>
        
        <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
          <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
        <% end %>

        <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
          <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
        <% end %>

        <%- if devise_mapping.omniauthable? %>
          <%- resource_class.omniauth_providers.each do |provider| %>
            <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
          <% end %>
        <% end %>
        <br>
      </div>
    </header>
    <%= yield %>
    <main>
      <% if current_user.present? %>
        <p>こんにちは、<%= current_user.name %>さん！</p>
          <% else %>
        <p>こんにちは、ゲストさん！</p>
      <% end %>
    </main>
  </body>
</html>

app/views/spots/index.html.erb
<% @spots.each do |spot| %>

  <%= spot.name %>
  
  <% if user_signed_in? %>

    <% if current_user.liked?(spot) %>
      <%= link_to spot_likes_path(spot), method: :delete do %>
        <span class="fa fa-heart liked-btn"></span>
        <span class="like__count"><%= spot.likes.count %></span>
      <% end %>
    <% else %>
      <%= link_to spot_likes_path(spot), method: :post do %>
        <span class="fa fa-heart-o unliked-btn"></span>
        <span class="like__count"><%= spot.likes.count %></span>
      <% end %>
    <% end %>
  <% else %>
    <span class="fa fa-heart-o liked-btn"></span>
    <span class="like__count"><%= spot.likes.count %></span>
  <% end %>
  <br>

<% end %>